### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by maxfi**
`local: true` should be passed as an object.

### CODE REVIEW

**Comment by alekseykulikov** [comment]
Thanks @maxfi! Now I'm working on brand new release of backbone.offline, and If you want to help with documentation, I will let you know, when it comes to documentation's phase. I'm really appreciate your help.

**Comment by maxfi** [comment]
Great @Ask11. I'd definitely like to help out.
I've also created a Backbone.Offline RequireJS app template that can be used with [Bower](http://twitter.github.com/bower/) for dependency management  and uses the [require.js optimization tool](http://requirejs.org/docs/optimization.html) to create a single javascript file. I'll upload it after some more testing.
I've also got some questions for you about the usage of Backbone.offline. Where is the best place to ask?
Thanks.

**Comment by alekseykulikov** [comment]
Cool progress.

> Where is the best place to ask?

Just ping me in skype: alekseys.kulikov. I'd like to chat.

**Comment by maxfi** [comment]
Cool. I'll get in touch tomorrow.

**Pull request merged**
