### PR TITLE
Manage dependencies with Bower

### PR DESCRIPTION
**Pull request by 0rca**
It makes easy to switch between versions of jquery, backbone, or underscore, or jasmine this module depends on.

### CODE REVIEW

**Comment by alekseykulikov** [comment]
@0rca it's so cool! You've just reopen bower for me! 
At the coming weekend, I'm going migrate to new storage https://github.com/ask11/storage, for better performance and support of IndexedDB. 
Could you help me to add bower support to the [storage](https://github.com/ask11/storage) in order to just add it to dependencies for backbone-offline. For now it builds on top of component.js, which has commonjs style.

**Comment by alekseykulikov** [comment]
`25 additions and 15,574 deletions.`
Stat of your pull-request makes me happy ;)

**Comment by 0rca** [comment]
Sure, I'll see what I can do once I have some spare minutes

**Comment by 0rca** [comment]
I'm glad I made someone happy today :)

**Pull request merged**
